# Generated by Django 2.0.3 on 2018-03-24 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='pick_up_time',
            new_name='trip_time',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_date',
        ),
    ]
