# Generated by Django 2.0.3 on 2018-03-27 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20180324_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('L', 'Late'), ('N', 'No Show'), ('U', 'Unsafe Behavior'), ('W', 'Did not wait')], max_length=1)),
                ('description', models.CharField(max_length=300)),
                ('complaint_filed', models.BooleanField(default=False)),
                ('filed_with', models.CharField(max_length=40)),
                ('filed_at', models.DateTimeField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='schedule.Trip')),
            ],
        ),
    ]
