# Generated by Django 2.0.3 on 2018-03-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='filed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='filed_with',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
