# Generated by Django 2.0.3 on 2018-03-31 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20180330_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', related_query_name='resident', to='schedule.Resident'),
        ),
    ]
