# Generated by Django 2.0.3 on 2018-03-31 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20180331_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', related_query_name='issue', to='schedule.Trip'),
        ),
    ]
