# Generated by Django 2.0.3 on 2018-05-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20180331_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_time',
            new_name='trip_datetime',
        ),
    ]
