# Generated by Django 2.0.3 on 2018-05-04 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20180502_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='appointment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
