# Generated by Django 2.0.3 on 2018-05-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_trip_appointment_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='room_number',
            field=models.CharField(default=508, max_length=5),
            preserve_default=False,
        ),
    ]
