# Generated by Django 2.0.3 on 2018-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_auto_20180506_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
